// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customers.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCustomers = `-- name: CountCustomers :one
SELECT count(*) FROM customers
WHERE ($1::text[] IS NULL OR status = ANY($1::text[]))
`

func (q *Queries) CountCustomers(ctx context.Context, statuses []string) (int64, error) {
	row := q.db.QueryRow(ctx, countCustomers, statuses)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers(user_id, full_name, birth_date, address, phone_number, citizenship) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, full_name, birth_date, address, phone_number, citizenship, status, created_at, updated_at
`

type CreateCustomerParams struct {
	UserID      uuid.UUID
	FullName    string
	BirthDate   pgtype.Date
	Address     string
	PhoneNumber string
	Citizenship string
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.UserID,
		arg.FullName,
		arg.BirthDate,
		arg.Address,
		arg.PhoneNumber,
		arg.Citizenship,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.BirthDate,
		&i.Address,
		&i.PhoneNumber,
		&i.Citizenship,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT id, user_id, full_name, birth_date, address, phone_number, citizenship, status, created_at, updated_at
FROM customers
WHERE id = $1
`

func (q *Queries) GetCustomerByID(ctx context.Context, id uuid.UUID) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByID, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.BirthDate,
		&i.Address,
		&i.PhoneNumber,
		&i.Citizenship,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByUserID = `-- name: GetCustomerByUserID :one
SELECT id, user_id, full_name, birth_date, address, phone_number, citizenship, status, created_at, updated_at
FROM customers
WHERE user_id = $1
`

func (q *Queries) GetCustomerByUserID(ctx context.Context, userID uuid.UUID) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByUserID, userID)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.BirthDate,
		&i.Address,
		&i.PhoneNumber,
		&i.Citizenship,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCustomers = `-- name: ListCustomers :many
SELECT id, user_id, full_name, birth_date, address, phone_number, citizenship, status, created_at, updated_at
FROM customers
WHERE ($1::text[] IS NULL OR status = ANY($1::text[]))
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListCustomersParams struct {
	Statuses []string
	Off      int32
	Lim      int32
}

func (q *Queries) ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomers, arg.Statuses, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Customer{}
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FullName,
			&i.BirthDate,
			&i.Address,
			&i.PhoneNumber,
			&i.Citizenship,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomer = `-- name: UpdateCustomer :one
UPDATE customers 
SET full_name = $2, birth_date = $3, address = $4, phone_number = $5, citizenship = $6, status = $7, updated_at = now() 
WHERE id = $1
RETURNING id, user_id, full_name, birth_date, address, phone_number, citizenship, status, created_at, updated_at
`

type UpdateCustomerParams struct {
	ID          uuid.UUID
	FullName    string
	BirthDate   pgtype.Date
	Address     string
	PhoneNumber string
	Citizenship string
	Status      string
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, updateCustomer,
		arg.ID,
		arg.FullName,
		arg.BirthDate,
		arg.Address,
		arg.PhoneNumber,
		arg.Citizenship,
		arg.Status,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.BirthDate,
		&i.Address,
		&i.PhoneNumber,
		&i.Citizenship,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCustomerStatus = `-- name: UpdateCustomerStatus :one
UPDATE customers 
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, user_id, full_name, birth_date, address, phone_number, citizenship, status, created_at, updated_at
`

type UpdateCustomerStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateCustomerStatus(ctx context.Context, arg UpdateCustomerStatusParams) (Customer, error) {
	row := q.db.QueryRow(ctx, updateCustomerStatus, arg.ID, arg.Status)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.BirthDate,
		&i.Address,
		&i.PhoneNumber,
		&i.Citizenship,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
