// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Customer struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	FullName    string
	BirthDate   pgtype.Date
	Address     string
	PhoneNumber string
	Citizenship string
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
