// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	GetCustomerByID(ctx context.Context, id uuid.UUID) (Customer, error)
	GetCustomerByUserID(ctx context.Context, userID uuid.UUID) (Customer, error)
	ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error)
	UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error)
	UpdateCustomerStatus(ctx context.Context, arg UpdateCustomerStatusParams) (Customer, error)
}

var _ Querier = (*Queries)(nil)
