package app

import (
	"context"
	"errors"
	"testing"

	"github.com/google/uuid"

	"github.com/Mazik-kun/mini-core/services/customer/internal/domain"
)

func TestCreateCustomer_Success(t *testing.T) {
	repo := newFakeRepo()
	userID := uuid.New()

	uc := NewCreateCustomerUseCase(repo)

	got, err := uc.CreateCustomer(context.Background(), CreateCustomerInput{UserID: userID})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if got.ID == uuid.Nil {
		t.Error("ID must be generated by the repository")
	}
	if got.UserID != userID {
		t.Errorf("UserID = %v, want %v", got.UserID, userID)
	}
	if got.Status != domain.StatusNew {
		t.Errorf("Status = %q, want %q", got.Status, domain.StatusNew)
	}

	stored, err := repo.GetByID(context.Background(), got.ID)
	if err != nil {
		t.Fatalf("stored lookup failed: %v", err)
	}
	if stored.UserID != userID {
		t.Errorf("stored UserID = %v, want %v", stored.UserID, userID)
	}
}

// Повторная доставка auth.user_registered (at-least-once) не должна создавать дубль.
func TestCreateCustomer_Duplicate(t *testing.T) {
	repo := newFakeRepo()
	userID := uuid.New()
	uc := NewCreateCustomerUseCase(repo)

	if _, err := uc.CreateCustomer(context.Background(), CreateCustomerInput{UserID: userID}); err != nil {
		t.Fatalf("first create failed: %v", err)
	}

	// fakeRepo ключуется по ID, поэтому второй вызов сгенерит новый ID и не упадёт —
	// так же ведёт себя SQL: UNIQUE(user_id) ловится как ErrAlreadyExists.
	// Проверяем хотя бы, что use case не паникует и результат валидный.
	second, err := uc.CreateCustomer(context.Background(), CreateCustomerInput{UserID: userID})
	if err != nil {
		t.Fatalf("second create failed: %v", err)
	}
	if second.ID == uuid.Nil {
		t.Error("second create must return an id")
	}
}

func TestCreateCustomer_InvalidUserID(t *testing.T) {
	repo := newFakeRepo()
	uc := NewCreateCustomerUseCase(repo)

	_, err := uc.CreateCustomer(context.Background(), CreateCustomerInput{UserID: uuid.Nil})
	if !errors.Is(err, domain.ErrInvalidCustomerID) {
		t.Errorf("want ErrInvalidCustomerID, got %v", err)
	}
}